// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// FileMetadata file metadata
// swagger:model FileMetadata
type FileMetadata struct {

	// digest
	// Read Only: true
	Digest string `json:"digest,omitempty"`

	// digest algorithm
	// Read Only: true
	DigestAlgorithm string `json:"digestAlgorithm,omitempty"`

	// id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// name
	// Read Only: true
	Name string `json:"name,omitempty"`

	// size
	// Read Only: true
	Size int64 `json:"size,omitempty"`

	// space
	// Read Only: true
	Space string `json:"space,omitempty"`
}

// Validate validates this file metadata
func (m *FileMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FileMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FileMetadata) UnmarshalBinary(b []byte) error {
	var res FileMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
