// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Module module
// swagger:model Module
type Module struct {

	// app name
	// Read Only: true
	AppName string `json:"appName,omitempty"`

	// created on
	// Read Only: true
	// Format: date-time
	CreatedOn strfmt.DateTime `json:"createdOn,omitempty"`

	// module name
	// Read Only: true
	ModuleName string `json:"moduleName,omitempty"`

	// provided dendency names
	// Read Only: true
	ProvidedDendencyNames []string `json:"providedDendencyNames"`

	// services
	// Read Only: true
	Services []string `json:"services"`

	// updated on
	// Read Only: true
	// Format: date-time
	UpdatedOn strfmt.DateTime `json:"updatedOn,omitempty"`

	// uris
	// Read Only: true
	Uris []string `json:"uris"`
}

// Validate validates this module
func (m *Module) Validate(formats strfmt.Registry) error {

	return nil
}


// MarshalBinary interface implementation
func (m *Module) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Module) UnmarshalBinary(b []byte) error {
	var res Module
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
